### ISSUE TITLE
Where is the dataset from?

### ISSUE THREAD

**Issue by jche629** [omkar-commits/Detereminig-Trustworhiness-of-IoT-crowdsensing-Data#1]
Hi,

I am new to SUMO. Just curious about in the _TrustWorthinessAlgorithm.ipynb_,  where are these files **reportcollision17-18.json** **userVotedData.json** and **usersdata.json** from?

How to get these data?

Thanks for your good repo!
Really want to learn!

Best,
jiazhi

**Comment by omkar-commits** [comment]
I have created my data set by referring different files. one of files you can get from Open Street Map.
